export const USER_REPOSITORY = 'USER_REPOSITORY'
export const CLAIM_REPOSITORY = 'CLAIM_REPOSITORY'
export const IDENTITY_REPOSITORY = 'IDENTITY_REPOSITORY'
export const ASSET_REPOSITORY = 'ASSET_REPOSITORY'
export const USER_ASSET_REPOSITORY = 'USER_ASSET_REPOSITORY'
export const OBLIGATION_REPOSITORY = 'OBLIGATION_REPOSITORY'
export const TOKEN_IDENTITY_REPOSITORY = 'TOKEN_IDENTITY_REPOSITORY'
export const TOKEN_CLAIM_REPOSITORY = 'TOKEN_CLAIM_REPOSITORY'
export const TOKEN_COMPLIANCE_REQUEST_REPOSITORY = 'TOKEN_COMPLIANCE_REQUEST_REPOSITORY'
export const DVD_TRANSFER_REPOSITORY = 'DVD_TRANSFER_REPOSITORY'

export const MAX_FILE_SIZE = 2000_000
export const FILE_TYPES = '.(png|jpeg|jpg|pdf|jfif)'